#include "mock_filesystem.h"

namespace openflash
{
    namespace esp32
    {
        mock_filesystem::mock_filesystem() :
            _ready(true)
        {
        }

        bool mock_filesystem::ready() const
        {
            return _ready;
        }

        bool mock_filesystem::list_directory(const std::string &path, std::vector<file_entry> &entries)
        {
            std::vector<file_entry> files = {
                file_entry(16777216, file_type::GBA_FILE, "Dragon Ball - Advanced Adventure (U)(Ongaku).gba"),
                file_entry(33554432, file_type::GBA_FILE, "Pokémon Donjon Mystère - Equipe de Secours Rouge.gba"),
                file_entry(16777216, file_type::GBA_FILE, "Pokemon Ruby (E).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Pokemon Sapphire (E).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Spider-Man 3 (France).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Taxi 3.gba"),
                file_entry(4194304, file_type::GBA_FILE, "V-Rally 3 (Europe) (En,Fr,De,Es,It).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Drill Dozer (USA).gba"),
                file_entry(4194304, file_type::GBA_FILE, "Mario Kart - Super Circuit (USA).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Mega Man Zero (USA, Europe).gba"),
                file_entry(16777216, file_type::GBA_FILE, "SA2.gba"),
                file_entry(220096, file_type::GBA_FILE, "GBARunner3.nds"),
                file_entry(131072, file_type::GBA_FILE, "out.sav"),
                file_entry(131072,
                           file_type::GBA_FILE,
                           "Pokemon Emerald Seaglass 3.0 (PokemonEmeraldseaglass.com).sav"),
                file_entry(16777216, file_type::GBA_FILE, "Pokemon - Emerald Version (USA, Europe).gba"),
                file_entry(131072, file_type::GBA_FILE, "0378 - Fire Emblem - Sealed Sword.sav"),
                file_entry(16778240, file_type::GBA_FILE, "Pokemon - Emerald Version (USA, Europe).gba_dump.gba"),
                file_entry(8425352, file_type::GBA_FILE, "MetroidZeroMission.gba"),
                file_entry(8384587, file_type::GBA_FILE, "SA.gba"),
                file_entry(
                    16777216,
                    file_type::GBA_FILE,
                    "2 Games in 1 - Castlevania Double Pack - Harmony of Dissonance & Aria of Sorrow (E) (M3).gba"),
                file_entry(16777216,
                           file_type::GBA_FILE,
                           "2 Games in 1 - Sonic Advance & Sonic Pinball Party (E) (M5).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Beyblade VForce - Ultimate Blader Jam (U).gba"),
                file_entry(4194304, file_type::GBA_FILE, "Breath of Fire (E).gba"),
                file_entry(4194304, file_type::GBA_FILE, "Breath of Fire II (E).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Cars (E) (M4).gba"),
                file_entry(4194304, file_type::GBA_FILE, "Contra Advance - The Alien Wars EX (E).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Donkey Kong Country (E).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Donkey Kong Country 2 (E) (M5).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Donkey Kong Country 3 (E) (M5).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Dragon Ball Z - Buu's Fury (U).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Dragon Ball Z - The Legacy of Goku (E) (M5) [!].gba"),
                file_entry(8388608, file_type::GBA_FILE, "Dragon Ball Z - The Legacy of Goku II (E) (M5).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Mario vs. Donkey Kong (E) (M5).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Megaman Battle Network (E) [!].gba"),
                file_entry(8388608, file_type::GBA_FILE, "Megaman Battle Network 2 (E).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Megaman Battle Network 3 - Blue Version (E).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Megaman Battle Network 4 - Red Sun (E).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Megaman Battle Network 5 - Team Colonel (E).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Megaman Battle Network 6 - Cybeast Falzar (E).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Megaman Zero (U).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Megaman Zero 2 (E).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Megaman Zero 3 (E).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Megaman Zero 4 (E).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Naruto - Ninja Council (U).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Naruto - Ninja Council 2 (U).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Sword of Mana (E).gba"),
                file_entry(1048576, file_type::GBA_FILE, "Classic NES Series - Metroid (U) (patched).gba"),
                file_entry(1048576, file_type::GBA_FILE, "Classic NES Series - Excitebike (U) (patched).gba"),
                file_entry(1048576, file_type::GBA_FILE, "Classic NES Series - Donkey Kong (U) (patched).gba"),
                file_entry(1048576, file_type::GBA_FILE, "Classic NES Series - Bomberman (U) (patched).gba"),
                file_entry(1048576, file_type::GBA_FILE, "Classic NES Series - Super Mario Bros. (U) (patched).gba"),
                file_entry(33554432, file_type::GBA_FILE, "Pokémon Heart and Soul SRAM (v2.0.2).gba"),
                file_entry(575204, file_type::GBA_FILE, "Flappy Bird (World) (Aftermarket) (Unl).gba"),
                file_entry(16777216,
                           file_type::GBA_FILE,
                           "Pokemon Pinball - Ruby & Sapphire (Europe) (En,Fr,De,Es,It).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Super Monkey Ball Jr. (Europe) (En,Fr,De,Es,It).gba"),
                file_entry(4194304, file_type::GBA_FILE, "ChuChu Rocket! (USA) (En,Ja,Fr,De,Es).gba"),
                file_entry(4194304, file_type::GBA_FILE, "FZERO.gba"),
                file_entry(33554432, file_type::GBA_FILE, "Pokémon Heart and Soul (v2.0.2).gba"),
                file_entry(8388608, file_type::GBA_FILE, "2 Games in One! - Dr. Mario + Puzzle League (USA).gba"),
                file_entry(16777216, file_type::GBA_FILE, "0378 - Fire Emblem - Sealed Sword.gba"),
                file_entry(8388608, file_type::GBA_FILE, "1840 - Metal Slug Advance (E)(TRSI).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Advance Wars Returns 3.3.gba"),
                file_entry(8388616, file_type::GBA_FILE, "AdvanceWarsStory1p84.gba"),
                file_entry(8388611, file_type::GBA_FILE, "AW2AndysAdventure2020Update.gba"),
                file_entry(16777216, file_type::GBA_FILE, "Boktai - The Sun Is in Your Hand (USA).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Boktai 2 - Solar Boy Django (USA).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Dr. Mario & Panel de Pon (Japan).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Game Boy Wars Advance 1+2 (Japan).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Golden Sun - The Lost Age (USA, Europe).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Golden Sun (USA, Europe).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Harvest Moon - Friends of Mineral Town (U) [!].gba"),
                file_entry(8388608, file_type::GBA_FILE, "Iridion II (USA).gba"),
                file_entry(16777216,
                           file_type::GBA_FILE,
                           "Mario & Luigi - Superstar Saga (Europe) (En,Fr,De,Es,It).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Mario Party Advance (Europe) (En,Fr,De,Es,It).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Mario Party Advance (USA).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Mother 1+2 (patched) (patched).gba"),
                file_entry(33554432, file_type::GBA_FILE, "Mother 3 (Eng. Translation 1.1).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Naruto - Ninja Council 2 (USA).gba"),
                file_entry(15540592, file_type::GBA_FILE, "Pokemon Emerald Seaglass (SC Software).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Pokemon Emerald Seaglass.gba"),
                file_entry(16777216, file_type::GBA_FILE, "Pokemon Liquid Crystal.gba"),
                file_entry(16777216, file_type::GBA_FILE, "Pokemon Perfect Leaf Green.gba"),
                file_entry(8388608, file_type::GBA_FILE, "Pokemon Pinball - Ruby & Sapphire.gba"),
                file_entry(16777216, file_type::GBA_FILE, "Pokemon Seaglass.gba"),
                file_entry(16777216, file_type::GBA_FILE, "Rhythm Tengoku (English Beta 13a).gba"),
                file_entry(33554432, file_type::GBA_FILE, "Shantae Risky Revolution.gba"),
                file_entry(33554432, file_type::GBA_FILE, "Yggdra Union - We'll Never Fight Alone (USA).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Astro Boy - Omega Factor (USA) (En,Ja,Fr,De,Es,It).gba"),
                file_entry(16777216, file_type::GBA_FILE, "EmeraldSeaglass_v3.0.gba"),
                file_entry(4756532, file_type::GBA_FILE, "PocketNESMenu.gba"),
                file_entry(65536, file_type::GBA_FILE, "Golden Sun (USA, Europe).sav"),
                file_entry(65536, file_type::GBA_FILE, "Golden Sun - The Lost Age (USA, Europe).sav"),
                file_entry(512, file_type::GBA_FILE, "Donkey Kong Country (E).sav"),
                file_entry(16777216, file_type::GBA_FILE, "Legend of Zelda, The - The Minish Cap (USA).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Mega Man Zero 2 (USA).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Mega Man Zero 3 (USA).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Mega Man Zero 4 (USA).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Metal Slug Advance (USA).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Metroid - Zero Mission (USA).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Metroid Fusion (USA, Australia).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Pokemon - LeafGreen Version (USA).gba"),
                file_entry(33554432,
                           file_type::GBA_FILE,
                           "Pokemon Mystery Dungeon - Red Rescue Team (USA, Australia).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Sonic Advance (USA) (En,Ja).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Sonic Advance 2 (USA) (En,Ja,Fr,De,Es,It).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Sonic Advance 3 (USA) (En,Ja,Fr,De,Es,It).gba"),
                file_entry(4194304, file_type::GBA_FILE, "Super Mario Advance (USA, Europe).gba"),
                file_entry(4194304,
                           file_type::GBA_FILE,
                           "Super Mario Advance 2 - Super Mario World (USA, Australia).gba"),
                file_entry(4194304, file_type::GBA_FILE, "Super Mario Advance 3 - Yoshi's Island (USA).gba"),
                file_entry(4194304, file_type::GBA_FILE, "Super Mario Advance 4 - Super Mario Bros. 3 (USA).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Wario Land 4 (USA, Europe).gba"),
                file_entry(8388608, file_type::GBA_FILE, "WarioWare, Inc. - Mega Microgame$! (USA).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Kirby & the Amazing Mirror (USA).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Kirby - Nightmare in Dream Land (USA).gba"),
                file_entry(67109, file_type::GBA_FILE, "Mega Man Zero (USA, Europe).ss1"),
                file_entry(32768, file_type::GBA_FILE, "Fire Emblem - The Sacred Stones (USA, Australia).sav"),
                file_entry(32768, file_type::GBA_FILE, "Kirby & the Amazing Mirror (USA).sav"),
                file_entry(32768, file_type::GBA_FILE, "Mega Man Zero (USA, Europe).sav"),
                file_entry(32768, file_type::GBA_FILE, "Mega Man Zero 2 (USA).sav"),
                file_entry(8192, file_type::GBA_FILE, "Legend of Zelda, The - The Minish Cap (USA).sav"),
                file_entry(16777216, file_type::GBA_FILE, "Fire Emblem - The Sacred Stones (USA, Australia).gba"),
                file_entry(8388608, file_type::GBA_FILE, "Advance Wars 2 - Black Hole Rising (U).gba"),
                file_entry(16777216, file_type::GBA_FILE, "Pokemon Pinball - Ruby & Sapphire Plus.gba"),
                file_entry(0, file_type::GBA_FILE, "Pokemon Pinball - Ruby & Sapphire (U) (V1.0) [hI].sav"),
            };
            entries.assign(files.begin(), files.end());
            return true;
        }
    }
}