#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GBA_DIR="$ROOT_DIR/gba"

JOBS="${JOBS:-$(nproc)}"

OPENFLASH_MOCK="${OPENFLASH_MOCK:-1}"
OPENFLASH_DEBUG="${OPENFLASH_DEBUG:-0}"
OPENFLASH_LUA="${OPENFLASH_LUA:-0}"

ROM="${OPENFLASH_ROM:-$GBA_DIR/gba.gba}"
ELF="${OPENFLASH_ELF:-$GBA_DIR/gba.elf}"

LUA_TEMPLATE="$GBA_DIR/lua/uart_template.lua"
LUA_RUNTIME="$GBA_DIR/build/uart_runtime.lua"

CLEAN_BUILD=0
GENERATE_MAPS=0
RUN_EMULATOR=0


usage()
{
    echo "Usage: $0 [options]"
    echo
    echo "Options:"
    echo "  --clean     Clean the GBA build before compiling"
    echo "  --maps      Regenerate C++ map files from TMX files before building"
    echo "  --run       Run the generated ROM with mGBA after building"
    echo "  --help      Show this help"
    echo
    echo "Environment:"
    echo "  JOBS=<n>"
    echo "  OPENFLASH_MOCK=0|1"
    echo "  OPENFLASH_DEBUG=0|1"
    echo "  OPENFLASH_LUA=0|1"
    echo "  OPENFLASH_ROM=<path>"
    echo "  OPENFLASH_ELF=<path>"
    echo "  MGBA=<path-or-command>"
    echo "  NM=<path-or-command>"
}


find_nm()
{
    if [ -n "${NM:-}" ]
    then
        printf '%s\n' "$NM"
        return
    fi

    if [ -n "${DEVKITARM:-}" ] && [ -x "$DEVKITARM/bin/arm-none-eabi-nm" ]
    then
        printf '%s\n' "$DEVKITARM/bin/arm-none-eabi-nm"
        return
    fi

    if [ -x "/opt/devkitpro/devkitARM/bin/arm-none-eabi-nm" ]
    then
        printf '%s\n' "/opt/devkitpro/devkitARM/bin/arm-none-eabi-nm"
        return
    fi

    if command -v arm-none-eabi-nm >/dev/null 2>&1
    then
        command -v arm-none-eabi-nm
        return
    fi

    echo "Error: arm-none-eabi-nm was not found." >&2
    echo "Set NM=/path/to/arm-none-eabi-nm if needed." >&2
    exit 1
}


find_mgba()
{
    if [ -n "${MGBA:-}" ]
    then
        printf '%s\n' "$MGBA"
        return
    fi

    if command -v mgba-qt >/dev/null 2>&1
    then
        command -v mgba-qt
        return
    fi

    echo "Error: mgba-qt was not found." >&2
    echo "Set MGBA=/path/to/mgba-qt if needed." >&2
    exit 1
}


generate_lua_runtime()
{
    if [ ! -f "$ELF" ]
    then
        echo "Error: ELF file not found:"
        echo "  $ELF"
        exit 1
    fi

    if [ ! -f "$LUA_TEMPLATE" ]
    then
        echo "Error: Lua template not found:"
        echo "  $LUA_TEMPLATE"
        exit 1
    fi

    local nm_tool
    nm_tool="$(find_nm)"

    local mailbox_hex

    # Do not exit awk early here.
    # With "set -o pipefail", exiting awk early can SIGPIPE nm and
    # terminate this script even though the mailbox symbol was found.
    mailbox_hex="$(
        "$nm_tool" -C "$ELF" |
            awk '$NF == "openflash::gba::mailbox" { mailbox = $1 } END { if (mailbox != "") print mailbox }'
    )"

    if [ -z "$mailbox_hex" ]
    then
        echo "Error: mailbox symbol was not found in:"
        echo "  $ELF"
        echo
        echo "Expected symbol:"
        echo "  openflash::gba::mailbox"
        echo
        echo "Make sure the GBA was built with OPENFLASH_LUA=1."
        exit 1
    fi

    if [[ ! "$mailbox_hex" =~ ^[0-9A-Fa-f]+$ ]]
    then
        echo "Error: invalid mailbox address returned by nm:"
        echo "  $mailbox_hex"
        exit 1
    fi

    local mailbox_address
    mailbox_address="0x${mailbox_hex^^}"

    mkdir -p "$(dirname "$LUA_RUNTIME")"

    python3 - "$LUA_TEMPLATE" "$LUA_RUNTIME" "$mailbox_address" <<'PY'
import re
import sys
from pathlib import Path

source_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])
mailbox_address = sys.argv[3]

source = source_path.read_text(encoding="utf-8")

pattern = (
    r"local\s+MAILBOX\s*=\s*"
    r"0x[0-9A-Fa-f]+\s*"
    r"--\s*CHANGE THIS"
)

replacement = (
    "local MAILBOX =\n"
    f"    {mailbox_address} -- AUTO-GENERATED BY build_gba.sh"
)

result, count = re.subn(
    pattern,
    replacement,
    source,
    count=1,
)

if count != 1:
    raise SystemExit(
        "Error: could not find the MAILBOX placeholder in uart.lua.\n"
        "Expected something equivalent to:\n"
        "local MAILBOX = 0x02000000 -- CHANGE THIS"
    )

output_path.write_text(
    result,
    encoding="utf-8",
)
PY

    echo
    echo "Lua mailbox runtime generated:"
    echo "  Symbol:  openflash::gba::mailbox"
    echo "  Address: $mailbox_address"
    echo "  Script:  $LUA_RUNTIME"
}


while [ $# -gt 0 ]
do
    case "$1" in
        --clean)
            CLEAN_BUILD=1
            ;;

        --maps)
            GENERATE_MAPS=1
            ;;

        --run)
            RUN_EMULATOR=1
            ;;

        --help|-h)
            usage
            exit 0
            ;;

        *)
            echo "Unknown option: $1"
            echo
            usage
            exit 1
            ;;
    esac

    shift
done


if [ "$CLEAN_BUILD" -eq 1 ]
then
    echo "Cleaning GBA build..."
    echo

    make \
        -C "$GBA_DIR" \
        clean
fi


if [ "$GENERATE_MAPS" -eq 1 ]
then
    echo "Generating GBA maps..."
    echo

    (
        cd "$GBA_DIR"
        python3 tools/tmx_to_cpp.py maps
    )
fi


echo "Building GBA..."
echo
echo "  OPENFLASH_MOCK=$OPENFLASH_MOCK"
echo "  OPENFLASH_DEBUG=$OPENFLASH_DEBUG"
echo "  OPENFLASH_LUA=$OPENFLASH_LUA"
echo "  JOBS=$JOBS"
echo


make \
    -C "$GBA_DIR" \
    -j"$JOBS" \
    OPENFLASH_MOCK="$OPENFLASH_MOCK" \
    OPENFLASH_DEBUG="$OPENFLASH_DEBUG" \
    OPENFLASH_LUA="$OPENFLASH_LUA"


if [ "$OPENFLASH_LUA" -eq 1 ]
then
    generate_lua_runtime
fi


if [ "$RUN_EMULATOR" -eq 1 ]
then
    if [ ! -f "$ROM" ]
    then
        echo "Error: ROM not found:"
        echo "  $ROM"
        exit 1
    fi

    MGBA_BIN="$(find_mgba)"

    echo
    echo "Starting mGBA..."
    echo "  ROM: $ROM"
    echo "  Frame size: 2x"

    if [ "$OPENFLASH_LUA" -eq 1 ]
    then
        if [ ! -f "$LUA_RUNTIME" ]
        then
            echo "Error: generated Lua runtime script not found:"
            echo "  $LUA_RUNTIME"
            exit 1
        fi

        echo "  Lua server enabled"
        echo "  Script: $LUA_RUNTIME"
        echo

        "$MGBA_BIN" \
            -2 \
            --script "$LUA_RUNTIME" \
            "$ROM"
    else
        echo "  Lua server disabled"
        echo

        "$MGBA_BIN" \
            -2 \
            "$ROM"
    fi
fi
